### ISSUE TITLE
Clarification: which is the right repository? 

### ISSUE THREAD

**Issue by chrisspiegl** [cpyarger/obs-midi#137]
Hello OBS Midi People, Fans, and Creators,

I was wondering which of the two obs-midi repositories is the most current as of right now? Which one should be considered the main repository for this project?

- https://github.com/Alzy/obs-midi
- https://github.com/cpyarger/obs-midi

I have read that both of you are the developers behind this, just wondering if it would make sense to combine them repositories so that the issues can be collected in one spot?

Parallel issue on the other repository: https://github.com/Alzy/obs-midi/issues/78

This also leads into the question of: how active is the development of this project? I am considering making videos about this OBS-Midi plugin and trying to make it more popular but if it's stale I will not do that.

Thank you and I am looking forward to getting a better understanding.

**Comment by AlexanderIsom** [comment]
From what i gather, this being the most up to date repository, i'd assume this is the main project repo, not sure if Alzy and Cpyarger are still working on this together or its souly Cpyarger now, but also from what i gather its a side project so development is cycles come and go, it's been in development for over a year or two, but when development is active, useful and really powerful changes happen, for example being able to use midi keys to control other plugins! examples of which are documented on cpyarger's youtube, i too would love for this to be a big plugin, if not a native part of obs i think it's that powerful and useful, especially for higher budget productions!

**Comment by chrisspiegl** [comment]
Hello @cpyarger, not sure why you just closed this?

I don't see any clarification except for the "probably the most up to date"?

I'd love to share more about this (and actually will publish a video soon on YouTube about this plugin).

But it'd be great to know what is going on at the moment.

Is there a place to get these kinds of news?

**Comment by cpyarger** [comment]
Chris,

This repo is the most up-to-date, I  currently am the only active
developer,  at this point progress is slow due to some life issues.

Currently, I have two major features to implement, followed by some code
refactoring and cleanup prior to the 1.0 release.

Those features are ;

A feedback system, The previously implemented method for feedback worked on
a limited number of devices, The new one is being designed to be able to
work with any midi device.

and a Macro system, Allowing multiple actions to be carried out with a
single midi event.

The biggest thing I need help with is finding another developer, or two
willing to lend a hand.  both alzy and I have been busy with work lately,
and I would love to have someone able to focus on one of the new features.

Warmest Regards,


Christopher P. Yarger

**Comment by chrisspiegl** [comment]
Hi @cpyarger, 
Thank you for the detailed response. I appreciate it and this gives me a good insight to what is going on (and I think that is also very important for others to see).

I recently published a video on Youtube about this plugin (https://youtu.be/rMtoIpk7olk) and I am happy to share more as things come out.

I am also very much looking forward to testing the feedback and macro system.

Sadly I am not well enough versed in C++ to help with development but I am keeping my eyes open for testing releases if there are any.

I am using the Behringer X-Touch Mini.

With that said: I absolutely understand slow development. I do code as well and produce youtube videos and with all that it can be overwhelming at time. I have tremendous respect for you for having this plugin out and working on it further.

Cheers and I am looking forward to hearing from you,

Chris

**Comment by cpyarger** [comment]
Hey Chris,

Great video!

I really appreciate it.

Just a quick clarification on the feedback. It was stable for the Beringer
devices. But it was because they support 1:1 feedback. Quite a few other
devices expect feedback on different channels or different message types.

The new feedback system will be providing a default 1:1 auto mapping. But
also with the ability to manually remap the feedback.

In the future on the roadmap will be device profiles to ease remapping.

I really appreciate the video. And I feel it will serve as a huge
inspiration to continue programming.

Personally I use the Beringer buttons in toggle mode rather than momentary.

Also. The knobs have buttons as well if you press down on them. I tend to
use those for muting the volume of the audio device that's tied to the
knobs (:

Have a great day and once again thank you for the video !!!!

**Comment by chrisspiegl** [comment]
You're welcome. I'll keep my eyes open as I mentioned.

I am using the buttons on the dials as well. Works great for resetting the value I change with the dial.

And I am looking forward to the new overhauled system.

If you have anything to test, as I mentioned, I am open and I subscribed to a bunch of issues on this repo to get notified when something goes up.

👍

In terms of feedback systems: I didn't know that there are these differences. That is really interesting. Gonna look out for that as I am also in the development of a tool to directly control my ATEM Mini with MIDI and the Behringer X-Touch Mini. Gonna see how that goes 🙈.
