### ISSUE TITLE
Create Videos regarding obs-midi

### ISSUE THREAD

**Issue by cpyarger** [cpyarger/obs-midi#32]

**Comment by cpyarger** [comment]
@esaiah I thought we could take the videos to a new thread (:

**Comment by esaiah** [comment]
I will make this happen!  By this weekend for sure.

**Comment by cpyarger** [comment]
Sweet!

**Comment by cpyarger** [comment]
> Sweet! I am mainly looking for, downloading, and installing obs-midi, showing off some of the features, or just giving a quick video review on obs-midi and its features and uses.

https://github.com/cpyarger/obs-midi/issues/22#issuecomment-779474567

**Comment by cpyarger** [comment]
If you can post a link to any videos, and a Video Thumbnail here It would be appreciated. I'll then add them to the https://obs-midi.org site

**Comment by chrisspiegl** [comment]
I just received my Behringer X-Touch Mini and am looking to make videos about it on [my Channel](https://youtube.com/ChrisSpiegl).

How active is the development of OBS-Midi and I'd also be interested in testing and providing feedback.

Sadly the languages this project are written in (code) are not something I am familiar with so writing code is currently not an option for me 🙈.

Looking forward to collaborating because I think it is important that a cross-platform OBS MIDI plugin rises up (I am on macOS).

**Comment by chrisspiegl** [comment]
I recently published a video about this Plugin and the Behringer X-Touch Mini. You can find it at: https://youtu.be/rMtoIpk7olk

[![](https://img.youtube.com/vi/rMtoIpk7olk/mqdefault.jpg)](https://youtu.be/rMtoIpk7olk)

I am looking forward to see the Macro System and Feedback system and will probably make videos about these as things come out.
